export default [
  {
    id: '1',
    title: 'Product 1',
    uri: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/1.jpg',
    avgRating: 4.5,
    price: 25.23,
    oldPrice: 30.23,
  },
  {
    id: '2',
    title: 'Product 2',
    uri: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/2.jpg',
    avgRating: 4.5,
    price: 25.23,
    oldPrice: 30.23,
  },
  {
    id: '3',
    title: 'Product 3',
    uri: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/3.jpg',
    avgRating: 4.5,
    price: 25.23,
    oldPrice: 30.23,
  },
  {
    id: '4',
    title: 'Product 4',
    uri: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/1.jpg',
    avgRating: 4.5,
    price: 25.23,
    oldPrice: 30.23,
  },
  {
    id: '5',
    title: 'Product 5',
    uri: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/2.jpg',
    avgRating: 4.5,
    price: 25.23,
    oldPrice: 30.23,
  },
  {
    id: '6',
    title: 'Product 6',
    uri: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/3.jpg',
    avgRating: 4.5,
    price: 25.23,
    oldPrice: 30.23,
  },
]