// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Response {
    id:          string;
    nombre:      string;
    marca:       string;
    descripcion: string;
    precio:      number;
    valoracion:  number;
    tipos:       Tipo[];
    imagen1:     string;
    imagen2:     string;
}

export interface Tipo {
    categoria: Categoria;
    clase:     Clase;
}

export enum Categoria {
    Monitores = "Monitores",
}

export enum Clase {
    Destacado = "destacado",
    Oferta = "oferta",
    Recomendado = "recomendado",
}
